baseURL: https://rony.dev
languageCode: en-us
defaultContentLanguage: en
title: Rony Batista
theme: cupper-hugo-theme

taxonomies:
  tag: tags

permalinks:
  post: /:filename

imaging:
  quality: 99

params:
  description: Rony Batista
  homeMetaContent: Homepage and blog for Rony Batista.
  dateFormat: Jan 2, 2006
  codePenUser: ronyb29
  defaultDarkTheme: true
  moveFooterToHeader: false
  utterances:
    repo: ronyb29/blog
    issueTerm: title
    theme: github-dark


menu:
  nav: 
    - name: About Me
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Twitter
      url: https://twitter.com/ronyb29
      weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2