baseURL = "http://rony.dev/"
languageCode = "en-us"
title = "Rony Batista"
theme = "cupper-hugo-theme"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Homepage and blog for Rony Batista"
  homeMetaContent = "Homepage and blog for Rony Batista"
  # footer = "Copyright 2019©"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "ronyb29"

[menu]
  [[menu.nav]]
    name = "About me"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5